name: Verify Action Pins

on:
  pull_request:
    paths:
      - ".github/workflows/**"

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: suzuki-shunsuke/pinact-action@latest
        with:
          verify: "true"
          fix: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
